baseURL = "https://xztaityozx.github.io/image-blog/"
languageCode = "ja-jp"
title = "Images"
theme = "book"
summayLength = 70
hasCJKLanguage = true

[taxonomies]
  tag = "tags"

[params]
  customCSS = ["/css/custom.css"]
